/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'manparvesh' at '19/9/16 4:01 PM' with Gradle 2.9
 *
 * @author manparvesh, @date 19/9/16 4:01 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
